
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('class').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('class').insert({name: 'Alchemy Basics', subject_id:  1, professor_id: 11}),
        knex('class').insert({name: 'Introduction to Ancient Runes', subject_id:  2, professor_id: 1}),
        knex('class').insert({name: 'Advanced Ancient Runes', subject_id:  2, professor_id: 1}),
        knex('class').insert({name: 'Apparition', subject_id:  3, professor_id: 14}),
        knex('class').insert({name: 'Introduction to Arithmancy', subject_id:  4, professor_id: 10}),
        knex('class').insert({name: 'Advanced Numerology', subject_id:  4, professor_id: 10}),
        knex('class').insert({name: 'Advanced Arithmancy', subject_id:  4, professor_id: 10}),
        knex('class').insert({name: 'Wizard Art', subject_id:  5, professor_id: 12}),
        knex('class').insert({name: 'Muggle Art', subject_id:  5, professor_id: 12}),
        knex('class').insert({name: 'Astronomy 1', subject_id:  6, professor_id: 13}),
        knex('class').insert({name: 'Astronomy 2', subject_id:  6, professor_id: 13}),
        knex('class').insert({name: 'Astronomy 3', subject_id:  6, professor_id: 13}),
        knex('class').insert({name: 'Introduction to Care of Magical Creatures', subject_id:  7, professor_id: 5}),
        knex('class').insert({name: 'Creatures of the Deep', subject_id:  7, professor_id: 5}),
        knex('class').insert({name: 'Creatures of the Sky', subject_id:  7, professor_id: 5}),
        knex('class').insert({name: 'Creatures of the Earth', subject_id:  7, professor_id: 5}),
        knex('class').insert({name: 'Caring for Dangerous Creatures', subject_id:  7, professor_id: 5}),
        knex('class').insert({name: 'Introduction to Charms', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Charms of Engagement', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Charms for Self-Improvement', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Make Your Life Easier With Charms', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Charms for Health', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Transformations and Non-Verbal Spells', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Advanced Charms', subject_id:  8, professor_id: 4}),
        knex('class').insert({name: 'Introduction to Defence Against the Dark Arts', subject_id:  9, professor_id: 4}),
        knex('class').insert({name: 'Defence Against the Dark Arts 2', subject_id:  9, professor_id: 17}),
        knex('class').insert({name: 'Defence Against the Dark Arts 3', subject_id:  9, professor_id: 17}),
        knex('class').insert({name: 'Defence Against the Dark Arts 4', subject_id:  9, professor_id: 17}),
        knex('class').insert({name: 'Defence Against the Dark Arts 5', subject_id:  9, professor_id: 17}),
        knex('class').insert({name: 'Defence Against the Dark Arts 6', subject_id:  9, professor_id: 17}),
        knex('class').insert({name: 'Auror Certification', subject_id:  9, professor_id: 17}),
        knex('class').insert({name: 'Introduction to Divination', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Divination: Tea Time', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Divination: Palmistry', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Divination: Locating Your Third Eye', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Divination for the Gifted', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Xylomancy', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Divination for the Gifted', subject_id:  10, professor_id: 9}),
        knex('class').insert({name: 'Introduction to Flying', subject_id:  11, professor_id: 16}),
        knex('class').insert({name: 'Introduction to Herbology', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Aqua Herbology', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Desert and Mountain Herbology', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Greenhouse Care', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Everything You Need to Know About Dirt', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Advanced Herbology', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Dangerous Herbology', subject_id:  12, professor_id: 8}),
        knex('class').insert({name: 'Introduction to History of Magic', subject_id:  13, professor_id: 2}),
        knex('class').insert({name: 'The History of the Medieval Assembly of European Wizards & International Warlock Convention of 1289', subject_id: 13, professor_id: 2}),
        knex('class').insert({name: 'History of Witch Hunts', subject_id:  13, professor_id: 2}),
        knex('class').insert({name: 'Goblin Rebellions & Giant Wars', subject_id:  13, professor_id: 2}),
        knex('class').insert({name: 'Giant Wars In-depth', subject_id:  13, professor_id: 2}),
        knex('class').insert({name: 'History of Magic: Advanced Independent Study', subject_id:  13, professor_id: 2}),
        knex('class').insert({name: 'Introduction to Magical Theory', subject_id:  13, professor_id: 18}),
        knex('class').insert({name: 'Advanced Magical Theory', subject_id:  13, professor_id: 18}),
        knex('class').insert({name: 'Muggle Studies for Non-Muggleborns', subject_id:  15, professor_id: 3}),
        knex('class').insert({name: 'Cannot Believe It Is Not Magic: Wifi and Other Muggle Tech', subject_id:  15, professor_id: 3}),
        knex('class').insert({name: 'Muggle Perspectives and Blending Into the Muggle World', subject_id:  15, professor_id: 3}),
        knex('class').insert({name: 'Frog Choir', subject_id:  16, professor_id: 4}),
        knex('class').insert({name: 'Orchestra', subject_id:  16, professor_id: 10}),
        knex('class').insert({name: 'Introduction to Potions', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Environmental Potions', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Antidotes', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Safe Poison Brewing', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Performance-Enhancing Potions', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Potions: How to Pick the Best Ingredients', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Advanced Potions', subject_id:  17, professor_id: 7}),
        knex('class').insert({name: 'Introduction to Transfiguration', subject_id:  18, professor_id: 6}),
        knex('class').insert({name: 'Simple Element Transfiguration', subject_id:  18, professor_id: 6}),
        knex('class').insert({name: 'Intermediate Element Transfiguration', subject_id:  18, professor_id: 6}),
        knex('class').insert({name: 'Complex Element Transfiguration', subject_id:  18, professor_id: 6}),
        knex('class').insert({name: 'Animal-based Transfiguration', subject_id:  18, professor_id: 6}),
        knex('class').insert({name: 'Conjuring-based Transfiguration', subject_id:  18, professor_id: 6}),
        knex('class').insert({name: 'Advanced Transfiguration: Independent Study', subject_id:  18, professor_id: 6})
      ]);
    });
};
