
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('students').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('students').insert({name: 'Maverick Durgan', house_id: 4, year: 7, patronus: 'martingale'}),
        knex('students').insert({name: 'Laura Gerhold', house_id: 4, year: 7, patronus: 'penguin'}),
        knex('students').insert({name: 'Lorenzo Hayes', house_id: 4, year: 7, patronus: 'jaguar'}),
        knex('students').insert({name: 'Orland Stamm', house_id: 4, year: 7, patronus: 'sun fish'}),
        knex('students').insert({name: 'Okey Jacobs', house_id: 4, year: 7, patronus: 'giant squid'}),
        knex('students').insert({name: 'Johanna Haag', house_id: 4, year: 7, patronus: 'seahorse'}),
        knex('students').insert({name: 'Dallas Wintheiser', house_id: 4, year: 7, patronus: 'dachshund'}),
        knex('students').insert({name: 'Clovis Jones', house_id: 4, year: 7, patronus: 'clown fish'}),
        knex('students').insert({name: 'Dejah Wisozk', house_id: 4, year: 7, patronus: 'west highland terrier'}),
        knex('students').insert({name: 'Sienna Stoltenberg', house_id: 4, year: 7, patronus: 'seal'}),
        knex('students').insert({name: 'Katrina Kemmer', house_id: 4, year: 7, patronus: 'lemur'}),
        knex('students').insert({name: 'Oliver Wood', house_id: 4, year: 6, patronus: 'ox'}),
        knex('students').insert({name: 'Angelina Johnson', house_id: 4, year: 6, patronus: 'horse'}),
        knex('students').insert({name: 'Letha Moore Miss', house_id: 4, year: 6, patronus: 'alpaca'}),
        knex('students').insert({name: 'Leonora Lebsack', house_id: 4, year: 6, patronus: 'bison'}),
        knex('students').insert({name: 'Tyrese Runolfsdottir', house_id: 4, year: 6, patronus: 'coati'}),
        knex('students').insert({name: 'Hubert Fadel', house_id: 4, year: 6, patronus: 'rooster'}),
        knex('students').insert({name: 'Antwan Yundt', house_id: 4, year: 6, patronus: 'deer'}),
        knex('students').insert({name: 'Damon Predovic', house_id: 4, year: 6, patronus: 'rat'}),
        knex('students').insert({name: 'Meghan Halvorson', house_id: 4, year: 6, patronus: 'lizard'}),
        knex('students').insert({name: 'Ahmed Breitenberg', house_id: 4, year: 6, patronus: 'oryx'}),
        knex('students').insert({name: 'Tom Zieme', house_id: 4, year: 6, patronus: 'pig'}),
        knex('students').insert({name: 'Katie Bell', house_id: 4, year: 5, patronus: 'thorny devil'}),
        knex('students').insert({name: 'Fred Weasley', house_id: 4, year: 5, patronus: 'porpoise'}),
        knex('students').insert({name: 'George Weasley', house_id: 4, year: 5, patronus: 'bighorn'}),
        knex('students').insert({name: 'Florida Weissnat', house_id: 4, year: 5, patronus: 'stallion'}),
        knex('students').insert({name: 'Lisette Kuhic', house_id: 4, year: 5, patronus: 'aardvark'}),
        knex('students').insert({name: 'Green MacGyver', house_id: 4, year: 5, patronus: 'reindeer'}),
        knex('students').insert({name: 'Brooklyn Schmitt', house_id: 4, year: 5, patronus: 'mole'}),
        knex('students').insert({name: 'Carlie Gutkowski', house_id: 4, year: 5, patronus: 'leopard'}),
        knex('students').insert({name: 'Darion Bergstrom', house_id: 4, year: 5, patronus: 'eagle owl'}),
        knex('students').insert({name: 'Mariana Jakubowski', house_id: 4, year: 5, patronus: 'hartebeest'}),
        knex('students').insert({name: 'Harold Anderson', house_id: 4, year: 5, patronus: 'bull'}),
        knex('students').insert({name: 'Lavender Brown', house_id: 4, year: 4, patronus: 'aoudad'}),
        knex('students').insert({name: 'Seamus Finnigan', house_id: 4, year: 4, patronus: 'mare'}),
        knex('students').insert({name: 'Dean Thomas', house_id: 4, year: 4, patronus: 'weasel'}),
        knex('students').insert({name: 'Fay Dunbar', house_id: 4, year: 4, patronus: 'basilisk'}),
        knex('students').insert({name: 'Hermione Granger', house_id: 4, year: 4, patronus: 'ermine'}),
        knex('students').insert({name: 'Ron Weasley', house_id: 4, year: 4, patronus: 'hare'}),
        knex('students').insert({name: 'Lee Jordan', house_id: 4, year: 4, patronus: 'gorilla'}),
        knex('students').insert({name: 'Neville Longbottom', house_id: 4, year: 4, patronus: 'fawn'}),
        knex('students').insert({name: 'Parvati Patil', house_id: 4, year: 4, patronus: 'ram'}),
        knex('students').insert({name: 'Harry Potter', house_id: 4, year: 4, patronus: 'stag'}),
        knex('students').insert({name: 'Dean Thomas', house_id: 4, year: 4, patronus: 'rhinoceros'}),
        knex('students').insert({name: 'Penelope Ziemann', house_id: 4, year: 3, patronus: 'moose'}),
        knex('students').insert({name: 'Meaghan Mayert', house_id: 4, year: 3, patronus: 'canary'}),
        knex('students').insert({name: 'Audie Donnelly', house_id: 4, year: 3, patronus: 'crocodile'}),
        knex('students').insert({name: 'Raven Bernhard', house_id: 4, year: 3, patronus: 'musk-ox'}),
        knex('students').insert({name: 'Leopoldo Olson', house_id: 4, year: 3, patronus: 'sloth'}),
        knex('students').insert({name: 'Kelley Cruickshank', house_id: 4, year: 3, patronus: 'armadillo'}),
        knex('students').insert({name: 'Celia Keefe', house_id: 4, year: 3, patronus: 'vicuna'}),
        knex('students').insert({name: 'Quincy Wuckert', house_id: 4, year: 3, patronus: 'addax'}),
        knex('students').insert({name: 'Leola Pfeffer', house_id: 4, year: 3, patronus: 'panda'}),
        knex('students').insert({name: 'Elvie Konopelski', house_id: 4, year: 3, patronus: 'giraffe'}),
        knex('students').insert({name: 'Ginny Weasley', house_id: 4, year: 3, patronus: 'finch'}),
        knex('students').insert({name: 'Colin Creevey', house_id: 4, year: 3, patronus: 'cat'}),
        knex('students').insert({name: 'Kareem Corkery', house_id: 4, year: 2, patronus: 'waterbuck'}),
        knex('students').insert({name: 'Consuelo Collier', house_id: 4, year: 2, patronus: 'civet'}),
        knex('students').insert({name: 'Edwin Pfeffer', house_id: 4, year: 2, patronus: 'marten'}),
        knex('students').insert({name: 'Keyshawn Jakubowski', house_id: 4, year: 2, patronus: 'shrew'}),
        knex('students').insert({name: 'Hellen Wehner', house_id: 4, year: 2, patronus: 'ground hog'}),
        knex('students').insert({name: 'Chelsey Considine', house_id: 4, year: 2, patronus: 'coyote'}),
        knex('students').insert({name: 'Zechariah Glover', house_id: 4, year: 2, patronus: 'sheep'}),
        knex('students').insert({name: 'Mac McDermott', house_id: 4, year: 2, patronus: 'gnu'}),
        knex('students').insert({name: 'Jada Fay', house_id: 4, year: 2, patronus: 'kitten'}),
        knex('students').insert({name: 'Marisa Schamberger', house_id: 4, year: 2, patronus: 'badger'}),
        knex('students').insert({name: 'Dennis Creevey', house_id: 4, year: 1, patronus: 'hippopotamus'}),
        knex('students').insert({name: 'Era Herzog', house_id: 4, year: 1, patronus: 'chameleon'}),
        knex('students').insert({name: 'Marjory Wehner', house_id: 4, year: 1, patronus: 'ewe'}),
        knex('students').insert({name: 'Grayson Breitenberg', house_id: 4, year: 1, patronus: 'chicken'}),
        knex('students').insert({name: 'Greyson Herman', house_id: 4, year: 1, patronus: 'lovebird'}),
        knex('students').insert({name: 'Barton Glover', house_id: 4, year: 1, patronus: 'guinea pig'}),
        knex('students').insert({name: 'Dina Jerde', house_id: 4, year: 1, patronus: 'mongoose'}),
        knex('students').insert({name: 'Gaston Hills', house_id: 4, year: 1, patronus: 'parrot'}),
        knex('students').insert({name: 'Evan Weimann', house_id: 4, year: 1, patronus: 'meerkat'}),
        knex('students').insert({name: 'Amparo Hane', house_id: 4, year: 1, patronus: 'opossum'}),
        knex('students').insert({name: 'Gina Lind', house_id: 4, year: 1, patronus: 'polar bear'}),
        knex('students').insert({name: 'Queenie Altenwerth', house_id: 4, year: 1, patronus: 'antelope'}),
        knex('students').insert({name: 'Pauline Kemmer Miss', house_id: 3, year: 7, patronus: 'wolverine'}),
        knex('students').insert({name: 'Aaliyah VonRueden', house_id: 3, year: 7, patronus: 'llama'}),
        knex('students').insert({name: 'Addison Stamm', house_id: 3, year: 7, patronus: 'whale'}),
        knex('students').insert({name: 'Norbert Konopelski', house_id: 3, year: 7, patronus: 'bald eagle'}),
        knex('students').insert({name: 'Roel Watsica', house_id: 3, year: 7, patronus: 'dog'}),
        knex('students').insert({name: 'Hudson Lueilwitz', house_id: 3, year: 7, patronus: 'eland'}),
        knex('students').insert({name: 'Desmond Simonis', house_id: 3, year: 7, patronus: 'doe'}),
        knex('students').insert({name: 'Icie Waelchi', house_id: 3, year: 7, patronus: 'quagga'}),
        knex('students').insert({name: 'Arch Jacobs', house_id: 3, year: 7, patronus: 'tiger'}),
        knex('students').insert({name: 'Lauryn Larkin', house_id: 3, year: 7, patronus: 'ape'}),
        knex('students').insert({name: 'Bryce Maggi', house_id: 3, year: 7, patronus: 'newt'}),
        knex('students').insert({name: 'Heather Parisian', house_id: 3, year: 6, patronus: 'mule'}),
        knex('students').insert({name: 'Brando Huels', house_id: 3, year: 6, patronus: 'skunk'}),
        knex('students').insert({name: 'Ethan Hudson', house_id: 3, year: 6, patronus: 'turtle'}),
        knex('students').insert({name: 'Karina Walker', house_id: 3, year: 6, patronus: 'alligator'}),
        knex('students').insert({name: 'Joe Ondricka', house_id: 3, year: 6, patronus: 'blue crab'}),
        knex('students').insert({name: 'Minerva Harris', house_id: 3, year: 6, patronus: 'starfish'}),
        knex('students').insert({name: 'Wilmer Hyatt', house_id: 3, year: 6, patronus: 'hedgehog'}),
        knex('students').insert({name: 'Tillman Paucek', house_id: 3, year: 6, patronus: 'yak'}),
        knex('students').insert({name: 'Myrna Emard', house_id: 3, year: 6, patronus: 'mynah bird'}),
        knex('students').insert({name: 'Lavina Kling', house_id: 3, year: 6, patronus: 'wildcat'}),
        knex('students').insert({name: 'Tiffany Durgan', house_id: 3, year: 6, patronus: 'budgerigar'}),
        knex('students').insert({name: 'Caterina Trantow', house_id: 3, year: 5, patronus: 'warthog'}),
        knex('students').insert({name: 'Maynard Miller', house_id: 3, year: 5, patronus: 'chimpanzee'}),
        knex('students').insert({name: 'Elmer Thompson', house_id: 3, year: 5, patronus: 'cow'}),
        knex('students').insert({name: 'Adan Eichmann', house_id: 3, year: 5, patronus: 'salamander'}),
        knex('students').insert({name: 'Clair Kunde', house_id: 3, year: 5, patronus: 'gazelle'}),
        knex('students').insert({name: 'Euna Howell', house_id: 3, year: 5, patronus: 'okapi'}),
        knex('students').insert({name: 'Roberta Renner', house_id: 3, year: 5, patronus: 'impala'}),
        knex('students').insert({name: 'Lorine Schiller', house_id: 3, year: 5, patronus: 'dormouse'}),
        knex('students').insert({name: 'Ansel Moore', house_id: 3, year: 5, patronus: 'beaver'}),
        knex('students').insert({name: 'Dedric Abbott', house_id: 3, year: 5, patronus: 'porcupine'}),
        knex('students').insert({name: 'Noemi Schumm', house_id: 3, year: 5, patronus: 'elephant'}),
        knex('students').insert({name: 'Conor Mann', house_id: 3, year: 4, patronus: 'squirrel'}),
        knex('students').insert({name: 'Cary Wyman Dr.', house_id: 3, year: 4, patronus: 'gila monster'}),
        knex('students').insert({name: 'Rickie Feest', house_id: 3, year: 4, patronus: 'lynx'}),
        knex('students').insert({name: 'Janet Roob', house_id: 3, year: 4, patronus: 'tapir'}),
        knex('students').insert({name: 'Nikki Schroeder', house_id: 3, year: 4, patronus: 'fox'}),
        knex('students').insert({name: 'Amir Reilly', house_id: 3, year: 4, patronus: 'pronghorn'}),
        knex('students').insert({name: 'Draco Malfoy', house_id: 3, year: 4, patronus: 'frog'}),
        knex('students').insert({name: 'Vincent Crabbe', house_id: 3, year: 4, patronus: 'baboon'}),
        knex('students').insert({name: 'Gregory Goyle', house_id: 3, year: 4, patronus: 'gopher'}),
        knex('students').insert({name: 'Pansy Parkinson', house_id: 3, year: 4, patronus: 'hyena'}),
        knex('students').insert({name: 'Nikki Schroeder', house_id: 3, year: 4, patronus: 'crow'}),
        knex('students').insert({name: 'Amica Reilly', house_id: 3, year: 4, patronus: 'walrus'}),
        knex('students').insert({name: 'Adelle Bartoletti', house_id: 3, year: 3, patronus: 'dingo'}),
        knex('students').insert({name: 'Albin Conn', house_id: 3, year: 3, patronus: 'dromedary'}),
        knex('students').insert({name: 'Shanel Gottlieb', house_id: 3, year: 3, patronus: 'dung beetle'}),
        knex('students').insert({name: 'Grayce Cruickshank', house_id: 3, year: 3, patronus: 'silver fox'}),
        knex('students').insert({name: 'Mateo Toy', house_id: 3, year: 3, patronus: 'hog'}),
        knex('students').insert({name: 'Alivia Thiel', house_id: 3, year: 3, patronus: 'jerboa'}),
        knex('students').insert({name: 'Dana Zulauf', house_id: 3, year: 3, patronus: 'puma'}),
        knex('students').insert({name: 'Gilberto Reinger', house_id: 3, year: 3, patronus: 'orangutan'}),
        knex('students').insert({name: 'Lydia Jerde', house_id: 3, year: 3, patronus: 'jackal'}),
        knex('students').insert({name: 'Charity Lockman', house_id: 3, year: 3, patronus: 'lemur'}),
        knex('students').insert({name: 'Louvenia Swift', house_id: 3, year: 3, patronus: 'mustang'}),
        knex('students').insert({name: 'Liliane Farrell', house_id: 3, year: 2, patronus: 'grizzly bear'}),
        knex('students').insert({name: 'Ursula Kutch', house_id: 3, year: 2, patronus: 'colt'}),
        knex('students').insert({name: 'Shawn Stiedemann', house_id: 3, year: 2, patronus: 'burro'}),
        knex('students').insert({name: 'Korey Blick', house_id: 3, year: 2, patronus: 'peccary'}),
        knex('students').insert({name: 'Bernhard Greenfelder', house_id: 3, year: 2, patronus: 'toad'}),
        knex('students').insert({name: 'Tanner Ferry', house_id: 3, year: 2, patronus: 'boar'}),
        knex('students').insert({name: 'Lionel Kuhn', house_id: 3, year: 2, patronus: 'steer'}),
        knex('students').insert({name: 'Evalyn Herzog', house_id: 3, year: 2, patronus: 'wombat'}),
        knex('students').insert({name: 'Cleve Block', house_id: 3, year: 2, patronus: 'ocelot'}),
        knex('students').insert({name: 'Estel Balistreri', house_id: 3, year: 2, patronus: 'bumble bee'}),
        knex('students').insert({name: 'Delpha Roob', house_id: 3, year: 2, patronus: 'zebra'}),
        knex('students').insert({name: 'Major Huels', house_id: 3, year: 1, patronus: 'elk'}),
        knex('students').insert({name: 'Virginie Streich', house_id: 3, year: 1, patronus: 'parakeet'}),
        knex('students').insert({name: 'Bobbie Swift', house_id: 3, year: 1, patronus: 'iguana'}),
        knex('students').insert({name: 'Abbey Fritsch', house_id: 3, year: 1, patronus: 'chinchilla'}),
        knex('students').insert({name: 'Matteo Fisher', house_id: 3, year: 1, patronus: 'buffalo'}),
        knex('students').insert({name: 'Ransom Tillman', house_id: 3, year: 1, patronus: 'musk deer'}),
        knex('students').insert({name: 'Alexandrine Kreiger', house_id: 3, year: 1, patronus: 'camel'}),
        knex('students').insert({name: 'Casimir Boyle', house_id: 3, year: 1, patronus: 'bat'}),
        knex('students').insert({name: 'Melisa Von', house_id: 3, year: 1, patronus: 'capybara'}),
        knex('students').insert({name: 'Cristian Haley', house_id: 3, year: 1, patronus: 'panther'}),
        knex('students').insert({name: 'Deondre Satterfield', house_id: 3, year: 1, patronus: 'mandrill'}),
        knex('students').insert({name: 'Orie Rosenbaum', house_id: 1, year: 7, patronus: 'mouse'}),
        knex('students').insert({name: 'Rodger Eichmann', house_id: 1, year: 7, patronus: 'raccoon'}),
        knex('students').insert({name: 'Ezra Dibbert', house_id: 1, year: 7, patronus: 'mountain goat'}),
        knex('students').insert({name: 'Rick Green', house_id: 1, year: 7, patronus: 'snake'}),
        knex('students').insert({name: 'Myah Dickens', house_id: 1, year: 7, patronus: 'duckbill platypus'}),
        knex('students').insert({name: 'Halie Yundt', house_id: 1, year: 7, patronus: 'jaguar'}),
        knex('students').insert({name: 'Nelda Conroy', house_id: 1, year: 7, patronus: 'woodchuck'}),
        knex('students').insert({name: 'Waino Satterfield', house_id: 1, year: 7, patronus: 'monkey'}),
        knex('students').insert({name: 'Amina Keeling', house_id: 1, year: 7, patronus: 'wolf'}),
        knex('students').insert({name: 'Zoey White', house_id: 1, year: 7, patronus: 'snowy owl'}),
        knex('students').insert({name: 'Sincere Cummerata', house_id: 1, year: 7, patronus: 'lion'}),
        knex('students').insert({name: 'Stacy VonRueden', house_id: 1, year: 6, patronus: 'donkey'}),
        knex('students').insert({name: 'Cedric Diggory', house_id: 1, year: 6, patronus: 'kangaroo'}),
        knex('students').insert({name: 'Edison Keeling', house_id: 1, year: 6, patronus: 'goat'}),
        knex('students').insert({name: 'Noemi Emmerich', house_id: 1, year: 6, patronus: 'hamster'}),
        knex('students').insert({name: 'Dorothea Ruecker', house_id: 1, year: 6, patronus: 'ibex'}),
        knex('students').insert({name: 'Abdul Kemmer', house_id: 1, year: 6, patronus: 'prairie dog'}),
        knex('students').insert({name: 'Geovany Becker', house_id: 1, year: 6, patronus: 'seal'}),
        knex('students').insert({name: 'Rebeka White', house_id: 1, year: 6, patronus: 'muskrat'}),
        knex('students').insert({name: 'Devin McGlynn', house_id: 1, year: 6, patronus: 'bunny'}),
        knex('students').insert({name: 'Ahmed Jakubowski', house_id: 1, year: 6, patronus: 'marmoset'}),
        knex('students').insert({name: 'Davion Ward', house_id: 1, year: 6, patronus: 'chamois'}),
        knex('students').insert({name: 'Raina Marks', house_id: 1, year: 5, patronus: 'fox'}),
        knex('students').insert({name: 'Sigurd Crooks', house_id: 1, year: 5, patronus: 'cheetah'}),
        knex('students').insert({name: 'Joshuah Klock', house_id: 1, year: 5, patronus: 'koala'}),
        knex('students').insert({name: 'Ryann Gutkowski', house_id: 1, year: 5, patronus: 'gemsbok'}),
        knex('students').insert({name: 'Darren Dietrich', house_id: 1, year: 5, patronus: 'otter'}),
        knex('students').insert({name: 'Montana Jaskolski', house_id: 1, year: 5, patronus: 'pony'}),
        knex('students').insert({name: 'Elbert Auer', house_id: 1, year: 5, patronus: 'bear'}),
        knex('students').insert({name: 'Cassie Harvey', house_id: 1, year: 5, patronus: 'springbok'}),
        knex('students').insert({name: 'Erin Stark', house_id: 1, year: 5, patronus: 'chipmunk'}),
        knex('students').insert({name: 'Ludwig Prosacc', house_id: 1, year: 5, patronus: 'cougar'}),
        knex('students').insert({name: 'Luna Lovegood', house_id: 1, year: 5, patronus: 'fish'}),
        knex('students').insert({name: 'Gaetano Kirlin', house_id: 1, year: 4, patronus: 'puppy'}),
        knex('students').insert({name: 'Ford Parisian', house_id: 1, year: 4, patronus: 'lamb'}),
        knex('students').insert({name: 'Elvera Labadie', house_id: 1, year: 4, patronus: 'anteater'}),
        knex('students').insert({name: 'Sister Thompson', house_id: 1, year: 4, patronus: 'argali'}),
        knex('students').insert({name: 'Adam Murazik', house_id: 1, year: 4, patronus: 'ferret'}),
        knex('students').insert({name: 'Jeremie Sanford', house_id: 1, year: 4, patronus: 'rabbit'}),
        knex('students').insert({name: 'Jerome Kertzmann', house_id: 1, year: 4, patronus: 'zebu'}),
        knex('students').insert({name: 'Chesley Bednar', house_id: 1, year: 4, patronus: 'dugong'}),
        knex('students').insert({name: 'Nicholas Rutherford', house_id: 1, year: 4, patronus: 'octopus'}),
        knex('students').insert({name: 'Emiliano Osinski', house_id: 1, year: 4, patronus: 'ox'}),
        knex('students').insert({name: 'Joanny Tillman', house_id: 1, year: 4, patronus: 'horse'}),
        knex('students').insert({name: 'Frankie Herman', house_id: 1, year: 3, patronus: 'alpaca'}),
        knex('students').insert({name: 'Laverna Prosacc', house_id: 1, year: 3, patronus: 'bison'}),
        knex('students').insert({name: 'Markus Maggio', house_id: 1, year: 3, patronus: 'coati'}),
        knex('students').insert({name: 'Austyn Schulist', house_id: 1, year: 3, patronus: 'rooster'}),
        knex('students').insert({name: 'Marjory Reynolds', house_id: 1, year: 3, patronus: 'deer'}),
        knex('students').insert({name: 'Romaine Block', house_id: 1, year: 3, patronus: 'rat'}),
        knex('students').insert({name: 'Jammie Parker', house_id: 1, year: 3, patronus: 'lizard'}),
        knex('students').insert({name: 'Emerson Heaney', house_id: 1, year: 3, patronus: 'oryx'}),
        knex('students').insert({name: 'Tavares Okuneva', house_id: 1, year: 3, patronus: 'pig'}),
        knex('students').insert({name: 'Lilla Dach', house_id: 1, year: 3, patronus: 'thorny devil'}),
        knex('students').insert({name: 'Vernie Kuhic', house_id: 1, year: 3, patronus: 'porpoise'}),
        knex('students').insert({name: 'Ollie Dare', house_id: 1, year: 2, patronus: 'bighorn'}),
        knex('students').insert({name: 'Kailee Lind', house_id: 1, year: 2, patronus: 'stallion'}),
        knex('students').insert({name: 'Michale Homenick', house_id: 1, year: 2, patronus: 'aardvark'}),
        knex('students').insert({name: 'Carmine Price', house_id: 1, year: 2, patronus: 'reindeer'}),
        knex('students').insert({name: 'Elmo Nienow', house_id: 1, year: 2, patronus: 'mole'}),
        knex('students').insert({name: 'Katrine Pfeffer', house_id: 1, year: 2, patronus: 'leopard'}),
        knex('students').insert({name: 'Chanelle Cartwright', house_id: 1, year: 2, patronus: 'eagle owl'}),
        knex('students').insert({name: 'Summer Abshire', house_id: 1, year: 2, patronus: 'hartebeest'}),
        knex('students').insert({name: 'Candido Dare', house_id: 1, year: 2, patronus: 'bull'}),
        knex('students').insert({name: 'Ephraim Hickle', house_id: 1, year: 2, patronus: 'aoudad'}),
        knex('students').insert({name: 'Ali Heller', house_id: 1, year: 2, patronus: 'mare'}),
        knex('students').insert({name: 'Stanley Cummerata', house_id: 1, year: 1, patronus: 'weasel'}),
        knex('students').insert({name: 'Rory Wuckert', house_id: 1, year: 1, patronus: 'basilisk'}),
        knex('students').insert({name: 'Herta Rowe', house_id: 1, year: 1, patronus: 'ermine'}),
        knex('students').insert({name: 'Kadin Lemke', house_id: 1, year: 1, patronus: 'hare'}),
        knex('students').insert({name: 'Zita DuBuque', house_id: 1, year: 1, patronus: 'gorilla'}),
        knex('students').insert({name: 'Barbara Stanton', house_id: 1, year: 1, patronus: 'fawn'}),
        knex('students').insert({name: 'Deven Williamson', house_id: 1, year: 1, patronus: 'ram'}),
        knex('students').insert({name: 'Adonis Pouros', house_id: 1, year: 1, patronus: 'mink'}),
        knex('students').insert({name: 'Mallory Okuneva', house_id: 1, year: 1, patronus: 'rhinoceros'}),
        knex('students').insert({name: 'Fay Sipes', house_id: 1, year: 1, patronus: 'moose'}),
        knex('students').insert({name: 'Izabella Feil', house_id: 1, year: 1, patronus: 'canary'}),
        knex('students').insert({name: 'Gregory DuBuque', house_id: 2, year: 7, patronus: 'crocodile'}),
        knex('students').insert({name: 'Mikel Macejkovic', house_id: 2, year: 7, patronus: 'musk-ox'}),
        knex('students').insert({name: 'Benny Robel', house_id: 2, year: 7, patronus: 'sloth'}),
        knex('students').insert({name: 'Jerod Nitzsche', house_id: 2, year: 7, patronus: 'armadillo'}),
        knex('students').insert({name: 'Rhoda Heaney', house_id: 2, year: 7, patronus: 'vicuna'}),
        knex('students').insert({name: 'Nigel Carter', house_id: 2, year: 7, patronus: 'addax'}),
        knex('students').insert({name: 'Juanita Heathcote', house_id: 2, year: 7, patronus: 'panda'}),
        knex('students').insert({name: 'Octavia Gleason', house_id: 2, year: 7, patronus: 'giraffe'}),
        knex('students').insert({name: 'Hattie Osinski', house_id: 2, year: 7, patronus: 'finch'}),
        knex('students').insert({name: 'Hershel Sporer', house_id: 2, year: 7, patronus: 'cat'}),
        knex('students').insert({name: 'Anahi Pagac', house_id: 2, year: 7, patronus: 'waterbuck'}),
        knex('students').insert({name: 'Gwendolyn Halvorson', house_id: 2, year: 6, patronus: 'civet'}),
        knex('students').insert({name: 'Blaise Waters', house_id: 2, year: 6, patronus: 'marten'}),
        knex('students').insert({name: 'Christiana McLaughlin', house_id: 2, year: 6, patronus: 'shrew'}),
        knex('students').insert({name: 'Leta Bahringer', house_id: 2, year: 6, patronus: 'ground hog'}),
        knex('students').insert({name: 'Rick Padberg', house_id: 2, year: 6, patronus: 'coyote'}),
        knex('students').insert({name: 'Immanuel Ankunding', house_id: 2, year: 6, patronus: 'sheep'}),
        knex('students').insert({name: 'Liliana Davis', house_id: 2, year: 6, patronus: 'gnu'}),
        knex('students').insert({name: 'Abigayle Predovic', house_id: 2, year: 6, patronus: 'kitten'}),
        knex('students').insert({name: 'Jarrett Cummings', house_id: 2, year: 6, patronus: 'badger'}),
        knex('students').insert({name: 'Perry Prosacc', house_id: 2, year: 6, patronus: 'hippopotamus'}),
        knex('students').insert({name: 'Monserrate Larson', house_id: 2, year: 6, patronus: 'chameleon'}),
        knex('students').insert({name: 'Alvina Conner', house_id: 2, year: 5, patronus: 'ewe'}),
        knex('students').insert({name: 'Aubrey Tremblay', house_id: 2, year: 5, patronus: 'chicken'}),
        knex('students').insert({name: 'Jedediah Buckridge', house_id: 2, year: 5, patronus: 'lovebird'}),
        knex('students').insert({name: 'Arnulfo Medhurst', house_id: 2, year: 5, patronus: 'guinea pig'}),
        knex('students').insert({name: 'Sarah Bednar', house_id: 2, year: 5, patronus: 'mongoose'}),
        knex('students').insert({name: 'Valentina Hand', house_id: 2, year: 5, patronus: 'parrot'}),
        knex('students').insert({name: 'Maximillia Walker', house_id: 2, year: 5, patronus: 'meerkat'}),
        knex('students').insert({name: 'Newell Eichmann', house_id: 2, year: 5, patronus: 'opossum'}),
        knex('students').insert({name: 'Dominic Dietrich', house_id: 2, year: 5, patronus: 'polar bear'}),
        knex('students').insert({name: 'Melba Marquardt', house_id: 2, year: 5, patronus: 'antelope'}),
        knex('students').insert({name: 'Candice Feest', house_id: 2, year: 5, patronus: 'wolverine'}),
        knex('students').insert({name: 'Zelma Lebsack', house_id: 2, year: 4, patronus: 'llama'}),
        knex('students').insert({name: 'Colten Kozey', house_id: 2, year: 4, patronus: 'whale'}),
        knex('students').insert({name: 'Hillary McLaughlin', house_id: 2, year: 4, patronus: 'bald eagle'}),
        knex('students').insert({name: 'Theresa Weimann', house_id: 2, year: 4, patronus: 'dog'}),
        knex('students').insert({name: 'Simeon Kihn', house_id: 2, year: 4, patronus: 'eland'}),
        knex('students').insert({name: 'Rosanna Conner', house_id: 2, year: 4, patronus: 'doe'}),
        knex('students').insert({name: 'Deion Hyatt', house_id: 2, year: 4, patronus: 'quagga'}),
        knex('students').insert({name: 'Cecilia Hettinger', house_id: 2, year: 4, patronus: 'tiger'}),
        knex('students').insert({name: 'Crawford Kozey', house_id: 2, year: 4, patronus: 'ape'}),
        knex('students').insert({name: 'Maida Renner', house_id: 2, year: 4, patronus: 'newt'}),
        knex('students').insert({name: 'Eliane Wintheiser', house_id: 2, year: 4, patronus: 'mule'}),
        knex('students').insert({name: 'Karina Jones', house_id: 2, year: 3, patronus: 'skunk'}),
        knex('students').insert({name: 'Broderick Runte', house_id: 2, year: 3, patronus: 'turtle'}),
        knex('students').insert({name: 'Owen Schimmel', house_id: 2, year: 3, patronus: 'alligator'}),
        knex('students').insert({name: 'Vanessa Raynor', house_id: 2, year: 3, patronus: 'blue crab'}),
        knex('students').insert({name: 'Oral Dibbert', house_id: 2, year: 3, patronus: 'starfish'}),
        knex('students').insert({name: 'Andreane Lindgren', house_id: 2, year: 3, patronus: 'hedgehog'}),
        knex('students').insert({name: 'Orville Shields', house_id: 2, year: 3, patronus: 'yak'}),
        knex('students').insert({name: 'Willy Schroeder', house_id: 2, year: 3, patronus: 'mynah bird'}),
        knex('students').insert({name: 'Tanya Hirthe', house_id: 2, year: 3, patronus: 'wildcat'}),
        knex('students').insert({name: 'Nedra Ankunding', house_id: 2, year: 3, patronus: 'budgerigar'}),
        knex('students').insert({name: 'Marietta Lueilwitz', house_id: 2, year: 3, patronus: 'warthog'}),
        knex('students').insert({name: 'Loy Hettinger', house_id: 2, year: 2, patronus: 'chimpanzee'}),
        knex('students').insert({name: 'Brain Sipes', house_id: 2, year: 2, patronus: 'cow'}),
        knex('students').insert({name: 'Blanche Cole', house_id: 2, year: 2, patronus: 'salamander'}),
        knex('students').insert({name: 'Freeda Auer', house_id: 2, year: 2, patronus: 'gazelle'}),
        knex('students').insert({name: 'Stephanie Kihn', house_id: 2, year: 2, patronus: 'okapi'}),
        knex('students').insert({name: 'Horace Keebler', house_id: 2, year: 2, patronus: 'impala'}),
        knex('students').insert({name: 'Monserrate Beier', house_id: 2, year: 2, patronus: 'dormouse'}),
        knex('students').insert({name: 'Antoinette Lueilwitz', house_id: 2, year: 2, patronus: 'beaver'}),
        knex('students').insert({name: 'Annabelle Funk', house_id: 2, year: 2, patronus: 'porcupine'}),
        knex('students').insert({name: 'Twila Schroeder', house_id: 2, year: 2, patronus: 'elephant'}),
        knex('students').insert({name: 'Jarred Wilderman', house_id: 2, year: 2, patronus: 'squirrel'}),
        knex('students').insert({name: 'Winnifred Krajcik', house_id: 2, year: 1, patronus: 'gila monster'}),
        knex('students').insert({name: 'Rico Hane', house_id: 2, year: 1, patronus: 'lynx'}),
        knex('students').insert({name: 'Bethany Reinger', house_id: 2, year: 1, patronus: 'tapir'}),
        knex('students').insert({name: 'Aric Bode', house_id: 2, year: 1, patronus: 'fox'}),
        knex('students').insert({name: 'Kasey Witting', house_id: 2, year: 1, patronus: 'pronghorn'}),
        knex('students').insert({name: 'Marguerite Watsica', house_id: 2, year: 1, patronus: 'frog'}),
        knex('students').insert({name: 'Mariane Watsica', house_id: 2, year: 1, patronus: 'baboon'}),
        knex('students').insert({name: 'Crystel Pagac', house_id: 2, year: 1, patronus: 'gopher'}),
        knex('students').insert({name: 'Shakira Renner', house_id: 2, year: 1, patronus: 'hyena'}),
        knex('students').insert({name: 'Darwin Wehner', house_id: 2, year: 1, patronus: 'crow'})
      ]);
    });
};
